-- Run this once in the Neon SQL Editor before deploying the API.
-- Passwords are bcrypt hashes generated by the backend; never insert a plaintext phone number.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  CREATE TYPE user_role AS ENUM ('ADMIN', 'USER');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role user_role NOT NULL DEFAULT 'USER',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_phone_format CHECK (phone ~ '^[0-9]{10,15}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_unique
  ON users (LOWER(username));
CREATE UNIQUE INDEX IF NOT EXISTS users_phone_unique ON users (phone);

-- Paste a bcrypt hash generated by the backend or a controlled provisioning tool.
-- Example roles: 'ADMIN' or 'USER'. Do not put a plaintext phone number here.
-- INSERT INTO users (username, phone, password_hash, role, must_change_password)
-- VALUES ('owner', '919876543210', '$2b$12$REPLACE_WITH_A_BCRYPT_HASH', 'ADMIN', TRUE);
