import * as bcrypt from 'bcrypt';
import { UnauthorizedException } from '@nestjs/common';
import { verify } from 'jsonwebtoken';

import { UserRole } from '../common/constants/user-role.enum';
import { User } from '../entities/user.entity';
import { JwtPayload } from './interfaces/jwt-payload.interface';
import { AuthService } from './auth.service';

describe('AuthService', () => {
  const usersService = { findByUsername: jest.fn() };
  const configService = {
    get: jest.fn((key: string) => {
      if (key === 'jwt.secret') return 'test-jwt-secret';
      if (key === 'jwt.expiresIn') return '15d';
      return undefined;
    }),
  };
  const existingAccountQuery = {
    where: jest.fn(),
    getOne: jest.fn(),
  };
  const usersRepository = {
    createQueryBuilder: jest.fn(),
    create: jest.fn(),
    save: jest.fn(),
  };
  const dealersRepository = { create: jest.fn(), save: jest.fn() };
  const manager = { getRepository: jest.fn() };
  const dataSource = { transaction: jest.fn() };
  const service = new AuthService(
    usersService as never,
    configService as never,
    dataSource as never,
  );
  const staffUser = {
    id: 'staff-1',
    username: 'Staff',
    phone: '7349083847',
    passwordHash: '',
    role: UserRole.STAFF,
    isActive: true,
    mustChangePassword: true,
  };

  beforeEach(async () => {
    jest.resetAllMocks();
    // PostgreSQL pgcrypto bcrypt hashes can use the $2a$ prefix. Node bcrypt
    // must accept the same valid initial password generated by PostgreSQL.
    staffUser.passwordHash = (await bcrypt.hash('7349083847', 10)).replace(
      /^\$2b\$/,
      '$2a$',
    );
    staffUser.isActive = true;
    usersService.findByUsername.mockResolvedValue(staffUser);
    configService.get.mockImplementation((key: string) => {
      if (key === 'jwt.secret') return 'test-jwt-secret';
      if (key === 'jwt.expiresIn') return '15d';
      return undefined;
    });
    existingAccountQuery.where.mockReturnValue(existingAccountQuery);
    existingAccountQuery.getOne.mockResolvedValue(null);
    usersRepository.createQueryBuilder.mockReturnValue(existingAccountQuery);
    usersRepository.create.mockImplementation((value) => value);
    usersRepository.save.mockImplementation(async (value) => ({
      ...value,
      id: 'dealer-user-1',
    }));
    dealersRepository.create.mockImplementation((value) => value);
    dealersRepository.save.mockImplementation(async (value) => ({
      ...value,
      id: 'dealer-1',
    }));
    manager.getRepository.mockImplementation((entity) =>
      entity === User ? usersRepository : dealersRepository,
    );
    dataSource.transaction.mockImplementation(async (callback) =>
      callback(manager),
    );
  });

  it('signs in an active STAFF user without requiring a dealer record', async () => {
    const result = await service.signIn({
      username: '  Staff  ',
      password: '  7349083847  ',
    });

    expect(usersService.findByUsername).toHaveBeenCalledWith('Staff');
    expect(typeof result.accessToken).toBe('string');
    expect(result.user).toEqual({
      id: 'staff-1',
      username: 'Staff',
      phone: '7349083847',
      role: UserRole.STAFF,
      mustChangePassword: true,
    });
    expect(JSON.stringify(result)).not.toContain(staffUser.passwordHash);
  });

  it('includes the STAFF role and username in the JWT payload', async () => {
    const result = await service.signIn({
      username: 'Staff',
      password: '7349083847',
    });
    const decoded: unknown = verify(result.accessToken, 'test-jwt-secret');
    const payload = decoded as JwtPayload;

    expect(payload).toMatchObject({
      sub: 'staff-1',
      username: 'Staff',
      role: UserRole.STAFF,
    });
  });

  it('returns 401 for a wrong STAFF password', async () => {
    await expect(
      service.signIn({ username: 'Staff', password: 'wrong-password' }),
    ).rejects.toBeInstanceOf(UnauthorizedException);
  });

  it('returns ACCOUNT_INACTIVE for an inactive STAFF account', async () => {
    staffUser.isActive = false;

    await expect(
      service.signIn({ username: 'Staff', password: '7349083847' }),
    ).rejects.toMatchObject({ code: 'ACCOUNT_INACTIVE' });
  });

  async function signInAs(role: UserRole, username: string, password: string) {
    usersService.findByUsername.mockResolvedValue({
      ...staffUser,
      id: `${role.toLowerCase()}-1`,
      username,
      phone: password,
      role,
      passwordHash: await bcrypt.hash(password, 10),
    });
    return service.signIn({ username, password });
  }

  it('authenticates an active dealer through the same credentials flow', async () => {
    await expect(
      signInAs(UserRole.USER, 'Dealer', '9000000001'),
    ).resolves.toMatchObject({
      user: { username: 'Dealer', role: UserRole.USER },
    });
  });

  it('authenticates an active administrator through the same credentials flow', async () => {
    await expect(
      signInAs(UserRole.ADMIN, 'Admin', '9000000002'),
    ).resolves.toMatchObject({
      user: { username: 'Admin', role: UserRole.ADMIN },
    });
  });

  it('registers a dealer with the dealer role only and returns a session', async () => {
    const result = await service.registerDealer({
      username: 'New Dealer',
      phone: '9000000003',
      shopName: 'New Dealer Electricals',
      password: 'secure-password',
      confirmPassword: 'secure-password',
      email: 'dealer@example.com',
      address: 'Main Road',
    });

    expect(usersRepository.create).toHaveBeenCalledWith(
      expect.objectContaining({
        role: UserRole.USER,
        isActive: true,
        mustChangePassword: false,
      }),
    );
    expect(dealersRepository.create).toHaveBeenCalledWith(
      expect.objectContaining({
        userId: 'dealer-user-1',
        businessName: 'New Dealer Electricals',
      }),
    );
    expect(result.user).toMatchObject({ role: UserRole.USER });
  });
});
